### ISSUE TITLE
Delayed Downgrade Option

### ISSUE THREAD

**Issue by davut** [pronamic/memberpress#5]
When we upgrade we don't see any issue it upgrades right away with proration, but when we downgrade we want to have a delay until the current plan ends (delayed downgrade) and when it reaches the end of the term it should switch to the selected downgrade option.

I couldn't find a way to use a delayed downgrade (we are using stripe). How we can implement it?

**Comment by remcotolsma** [comment]
This repository is just a mirror of the MemberPress plugin, i suggest you contact MemberPress support: https://memberpress.com/support/.

**Comment by davut** [comment]
@remcotolsma I contacted waiting for their response, but as a contributor do you have any idea about this? I would appreciate any suggestion. Thanks
